name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2    

    - name: Terraform Init
      working-directory: 'Deployment'
      run: terraform init

    - name: Terraform Validate
      working-directory: 'Deployment'
      run: terraform validate -no-color

    - name: Terraform Plan
      working-directory: '.Deployment'
      run: terraform plan -no-color
      continue-on-error: true  
        
    - name: Terraform Apply
      working-directory: 'Deployment'
      run: terraform apply -no-color
        