name: Build and Deploy App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: dotnet publish
      run: dotnet publish -c Release --runtime ubuntu.16.04-x64 -o ${{env.DOTNET_ROOT}}/myapp 

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build-package
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: build-package
        path: build
    
    - name: Generate deployment package
      run: |
        cd build
        zip -r ../deploy.zip .
  
    - name: Deploy to AWS Beanstalk
      id: deploy-to-beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        application_name: SampleApp
        environment_name: my-training-environment
        version_label: 1.2.1
        region: us-east-1
        deployment_package: deploy.zip