name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ my-training-environment.eba-qm43axes.us-east-1.elasticbeanstalk.com }}

  steps:
  - name: Download artifact from build job
    uses: actions/download-artifact@v2
    with:
      name: .net-app
 
  - name: Deploy to AWS
    id: deploy-to-beanstalk
    uses: einaregilsson/beanstalk-deploy@v20
    with:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      application_name: SampleApp
      environment_name: my-training-environment
      version_label: 12345
      region: us-east-1
      deployment_package: .
      